# yaml-language-server: $schema=https://json.schemastore.org/yamllint.json
rules:
  document-end: false
  document-start: false
  indentation:
    spaces: 2
    indent-sequences: false
  empty-lines:
    max: 1
    max-start: 0
    max-end: 0
  trailing-spaces: enable
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
  quoted-strings:
    required: only-when-needed
