# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: 3

tasks:
  default:
    aliases:
    - build
    desc: Builds all nix packages.
    cmd: nix-build default.nix --no-out-link
  build:*:
    desc: Test building a specific nix package.
    label: nix:build:{{ .NAME }}
    vars:
      NAME: '{{ index .MATCH 0 }}'
    cmd: nix-build default.nix -A {{ .NAME }} --no-out-link
  push:
    desc: Pushes built packages to the cache.
    cmd: nix-build default.nix --no-out-link | cachix push wwmoraes
  lint:
    desc: Lints all nix source files.
    deps:
    - for: sources
      task: lint:{{ .ITEM }}
    sources:
    - '**/*.nix'
  lint:*:
    desc: Lints a nix source file.
    label: lint:{{ .TARGET }}
    silent: true
    vars:
      TARGET: '{{ index .MATCH 0 }}'
    cmd: nil diagnostics {{ .TARGET }}
